# Form implementation generated from reading ui file './addon/UIForm/adv_conf_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(416, 343)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.flagScrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.flagScrollArea.setWidgetResizable(True)
        self.flagScrollArea.setObjectName("flagScrollArea")
        self.flagScrollAreaWidgetContents = QtWidgets.QWidget()
        self.flagScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 194, 263))
        self.flagScrollAreaWidgetContents.setObjectName("flagScrollAreaWidgetContents")
        self.flagScrollLayout = QtWidgets.QVBoxLayout(self.flagScrollAreaWidgetContents)
        self.flagScrollLayout.setObjectName("flagScrollLayout")
        self.flag_0_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_0_btn.setObjectName("flag_0_btn")
        self.flagScrollLayout.addWidget(self.flag_0_btn)
        self.flag_1_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_1_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ef4444;\n"
"}")
        self.flag_1_btn.setObjectName("flag_1_btn")
        self.flagScrollLayout.addWidget(self.flag_1_btn)
        self.flag_2_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_2_btn.setStyleSheet("QPushButton {\n"
"    background-color: #fb923c;\n"
"}")
        self.flag_2_btn.setObjectName("flag_2_btn")
        self.flagScrollLayout.addWidget(self.flag_2_btn)
        self.flag_3_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_3_btn.setStyleSheet("QPushButton {\n"
"    background-color: #4ade80;\n"
"}")
        self.flag_3_btn.setObjectName("flag_3_btn")
        self.flagScrollLayout.addWidget(self.flag_3_btn)
        self.flag_4_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_4_btn.setStyleSheet("QPushButton {\n"
"    background-color: #3b82f6;\n"
"}")
        self.flag_4_btn.setObjectName("flag_4_btn")
        self.flagScrollLayout.addWidget(self.flag_4_btn)
        self.flag_5_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_5_btn.setStyleSheet("QPushButton {\n"
"    background-color: #e879f9;\n"
"}")
        self.flag_5_btn.setObjectName("flag_5_btn")
        self.flagScrollLayout.addWidget(self.flag_5_btn)
        self.flag_6_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_6_btn.setStyleSheet("QPushButton {\n"
"    background-color: #2dd4bf;\n"
"}")
        self.flag_6_btn.setObjectName("flag_6_btn")
        self.flagScrollLayout.addWidget(self.flag_6_btn)
        self.flag_7_btn = QtWidgets.QPushButton(parent=self.flagScrollAreaWidgetContents)
        self.flag_7_btn.setStyleSheet("QPushButton {\n"
"    background-color: #a855f7;\n"
"}")
        self.flag_7_btn.setObjectName("flag_7_btn")
        self.flagScrollLayout.addWidget(self.flag_7_btn)
        self.flagScrollArea.setWidget(self.flagScrollAreaWidgetContents)
        self.gridLayout.addWidget(self.flagScrollArea, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 2, 1, 1)
        self.apiScrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.apiScrollArea.setWidgetResizable(True)
        self.apiScrollArea.setObjectName("apiScrollArea")
        self.apiScrollAreaWidgetContents = QtWidgets.QWidget()
        self.apiScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 194, 263))
        self.apiScrollAreaWidgetContents.setObjectName("apiScrollAreaWidgetContents")
        self.apiScrollLayout = QtWidgets.QVBoxLayout(self.apiScrollAreaWidgetContents)
        self.apiScrollLayout.setObjectName("apiScrollLayout")
        self.apiScrollArea.setWidget(self.apiScrollAreaWidgetContents)
        self.gridLayout.addWidget(self.apiScrollArea, 1, 1, 1, 1)
        self.descBtn = QtWidgets.QPushButton(parent=Dialog)
        self.descBtn.setObjectName("descBtn")
        self.gridLayout.addWidget(self.descBtn, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit, self.apiScrollArea)
        Dialog.setTabOrder(self.apiScrollArea, self.flagScrollArea)
        Dialog.setTabOrder(self.flagScrollArea, self.flag_0_btn)
        Dialog.setTabOrder(self.flag_0_btn, self.flag_1_btn)
        Dialog.setTabOrder(self.flag_1_btn, self.flag_2_btn)
        Dialog.setTabOrder(self.flag_2_btn, self.flag_3_btn)
        Dialog.setTabOrder(self.flag_3_btn, self.flag_4_btn)
        Dialog.setTabOrder(self.flag_4_btn, self.flag_5_btn)
        Dialog.setTabOrder(self.flag_5_btn, self.flag_6_btn)
        Dialog.setTabOrder(self.flag_6_btn, self.flag_7_btn)
        Dialog.setTabOrder(self.flag_7_btn, self.descBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.flag_0_btn.setText(_translate("Dialog", "flag:0"))
        self.flag_1_btn.setText(_translate("Dialog", "flag:1"))
        self.flag_2_btn.setText(_translate("Dialog", "flag:2"))
        self.flag_3_btn.setText(_translate("Dialog", "flag:3"))
        self.flag_4_btn.setText(_translate("Dialog", "flag:4"))
        self.flag_5_btn.setText(_translate("Dialog", "flag:5"))
        self.flag_6_btn.setText(_translate("Dialog", "flag:6"))
        self.flag_7_btn.setText(_translate("Dialog", "flag:7"))
        self.descBtn.setText(_translate("Dialog", "查看说明"))
