# Form implementation generated from reading ui file './addon/UIForm/template.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tplForm(object):
    def setupUi(self, tplForm):
        tplForm.setObjectName("tplForm")
        tplForm.resize(563, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(tplForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tplSetLayout = QtWidgets.QHBoxLayout()
        self.tplSetLayout.setObjectName("tplSetLayout")
        self.userTplButton = QtWidgets.QRadioButton(parent=tplForm)
        self.userTplButton.setChecked(True)
        self.userTplButton.setObjectName("userTplButton")
        self.tplButtonGroup = QtWidgets.QButtonGroup(tplForm)
        self.tplButtonGroup.setObjectName("tplButtonGroup")
        self.tplButtonGroup.addButton(self.userTplButton)
        self.tplSetLayout.addWidget(self.userTplButton)
        self.defaultTplButton = QtWidgets.QRadioButton(parent=tplForm)
        self.defaultTplButton.setObjectName("defaultTplButton")
        self.tplButtonGroup.addButton(self.defaultTplButton)
        self.tplSetLayout.addWidget(self.defaultTplButton)
        self.verticalLayout.addLayout(self.tplSetLayout)
        self.tplToolLayout = QtWidgets.QHBoxLayout()
        self.tplToolLayout.setObjectName("tplToolLayout")
        self.frontButton = QtWidgets.QRadioButton(parent=tplForm)
        self.frontButton.setChecked(True)
        self.frontButton.setObjectName("frontButton")
        self.partButtonGroup = QtWidgets.QButtonGroup(tplForm)
        self.partButtonGroup.setObjectName("partButtonGroup")
        self.partButtonGroup.addButton(self.frontButton)
        self.tplToolLayout.addWidget(self.frontButton)
        self.backButton = QtWidgets.QRadioButton(parent=tplForm)
        self.backButton.setObjectName("backButton")
        self.partButtonGroup.addButton(self.backButton)
        self.tplToolLayout.addWidget(self.backButton)
        self.cssButton = QtWidgets.QRadioButton(parent=tplForm)
        self.cssButton.setObjectName("cssButton")
        self.partButtonGroup.addButton(self.cssButton)
        self.tplToolLayout.addWidget(self.cssButton)
        self.saveButton = QtWidgets.QPushButton(parent=tplForm)
        self.saveButton.setObjectName("saveButton")
        self.tplToolLayout.addWidget(self.saveButton)
        self.previewButton = QtWidgets.QPushButton(parent=tplForm)
        self.previewButton.setObjectName("previewButton")
        self.tplToolLayout.addWidget(self.previewButton)
        self.verticalLayout.addLayout(self.tplToolLayout)
        self.plainEditText = QtWidgets.QPlainTextEdit(parent=tplForm)
        self.plainEditText.setObjectName("plainEditText")
        self.verticalLayout.addWidget(self.plainEditText)

        self.retranslateUi(tplForm)
        QtCore.QMetaObject.connectSlotsByName(tplForm)

    def retranslateUi(self, tplForm):
        _translate = QtCore.QCoreApplication.translate
        tplForm.setWindowTitle(_translate("tplForm", "Form"))
        self.userTplButton.setText(_translate("tplForm", "当前"))
        self.defaultTplButton.setText(_translate("tplForm", "默认"))
        self.frontButton.setText(_translate("tplForm", "Front"))
        self.backButton.setText(_translate("tplForm", "Back"))
        self.cssButton.setText(_translate("tplForm", "CSS"))
        self.saveButton.setText(_translate("tplForm", "保存"))
        self.previewButton.setText(_translate("tplForm", "预览"))
