# Form implementation generated from reading ui file './addon/UIForm/template.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tplForm(object):
    def setupUi(self, tplForm):
        tplForm.setObjectName("tplForm")
        tplForm.resize(600, 520)
        tplForm.setStyleSheet("QPlainTextEdit#plainEditText {\n"
"    font-family: Consolas, \'Fira Code\', \'Courier New\', monospace;\n"
"}\n"
"QPlainTextEdit#plainEditText:read-only {\n"
"    background-color: #f1f3f5;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(tplForm)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tplSetLayout = QtWidgets.QHBoxLayout()
        self.tplSetLayout.setSpacing(12)
        self.tplSetLayout.setObjectName("tplSetLayout")
        self.dbTplButton = QtWidgets.QRadioButton(parent=tplForm)
        self.dbTplButton.setChecked(True)
        self.dbTplButton.setObjectName("dbTplButton")
        self.tplButtonGroup = QtWidgets.QButtonGroup(tplForm)
        self.tplButtonGroup.setObjectName("tplButtonGroup")
        self.tplButtonGroup.addButton(self.dbTplButton)
        self.tplSetLayout.addWidget(self.dbTplButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tplSetLayout.addItem(spacerItem)
        self.previewButton = QtWidgets.QPushButton(parent=tplForm)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.HelpAbout)
        self.previewButton.setIcon(icon)
        self.previewButton.setObjectName("previewButton")
        self.tplSetLayout.addWidget(self.previewButton)
        self.saveButton = QtWidgets.QPushButton(parent=tplForm)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.HelpAbout)
        self.saveButton.setIcon(icon)
        self.saveButton.setIconSize(QtCore.QSize(16, 16))
        self.saveButton.setObjectName("saveButton")
        self.tplSetLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.tplSetLayout)
        self.tplPartLayout = QtWidgets.QHBoxLayout()
        self.tplPartLayout.setSpacing(16)
        self.tplPartLayout.setObjectName("tplPartLayout")
        self.frontButton = QtWidgets.QRadioButton(parent=tplForm)
        self.frontButton.setChecked(True)
        self.frontButton.setObjectName("frontButton")
        self.partButtonGroup = QtWidgets.QButtonGroup(tplForm)
        self.partButtonGroup.setObjectName("partButtonGroup")
        self.partButtonGroup.addButton(self.frontButton)
        self.tplPartLayout.addWidget(self.frontButton)
        self.backButton = QtWidgets.QRadioButton(parent=tplForm)
        self.backButton.setObjectName("backButton")
        self.partButtonGroup.addButton(self.backButton)
        self.tplPartLayout.addWidget(self.backButton)
        self.cssButton = QtWidgets.QRadioButton(parent=tplForm)
        self.cssButton.setObjectName("cssButton")
        self.partButtonGroup.addButton(self.cssButton)
        self.tplPartLayout.addWidget(self.cssButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tplPartLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.tplPartLayout)
        self.plainEditText = QtWidgets.QPlainTextEdit(parent=tplForm)
        self.plainEditText.setObjectName("plainEditText")
        self.verticalLayout.addWidget(self.plainEditText)

        self.retranslateUi(tplForm)
        QtCore.QMetaObject.connectSlotsByName(tplForm)

    def retranslateUi(self, tplForm):
        _translate = QtCore.QCoreApplication.translate
        tplForm.setWindowTitle(_translate("tplForm", "Form"))
        self.dbTplButton.setText(_translate("tplForm", "当前模板"))
        self.previewButton.setToolTip(_translate("tplForm", "预览插件内置固定样本，非真实数据"))
        self.previewButton.setText(_translate("tplForm", "预览"))
        self.saveButton.setToolTip(_translate("tplForm", "将所选模板保存成当前模板。注意，新增笔记的字段值新增了 class 用以控制样式，但已保存的字段值不会改变"))
        self.saveButton.setText(_translate("tplForm", "保存"))
        self.frontButton.setText(_translate("tplForm", "Front"))
        self.backButton.setText(_translate("tplForm", "Back"))
        self.cssButton.setText(_translate("tplForm", "CSS"))
